### ISSUE TITLE
Send multiple attachments to each recipient on bulk send

### ISSUE THREAD

**Issue by nexthor** [socketlabs/socketlabs-csharp#4]
right now you can send only one attachment for all batch of emails on a bulk message, but, what if i need to send to these bulk message a different attachment for each recipient?

**Comment by MattReibach** [comment]
Unfortunately the SocketLabs Injection API endpoint (`https://inject.socketlabs.com/api/v1/email`) does not support sending a unique attachment to each recipient in a bulk message.  I've passed this feedback to our team.  If the Injection API is ever updated to allow this functionality we'll be sure to update the C# library to add the feature as well.
